version: "3.9"
services:
  minio:
    image: minio/minio
    command: server /data
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: data
        target: /data
volumes:
  data:
