version: "3.9"
services:
  app:
    image: alpine
    command: sh -c 'apk add sqlite; sleep 3155760000'
    volumes:
      - type: volume
        source: data
        target: /data
  litestream:
    image: nickadam/litestream
    build:
      context: docker
      dockerfile: Dockerfile
    command: replicate
    environment:
      LITESTREAM_ACCESS_KEY_ID: minioadmin
      LITESTREAM_SECRET_ACCESS_KEY_FILE: /run/secrets/miniosecret
      LITESTREAM_CONFIG_CONTENT: |
        dbs:
          - path: /data/db.sqlite3
            replicas:
              - type: s3
                bucket: app
                path: db
                endpoint: http://minio:9000
    volumes:
      - type: volume
        source: data
        target: /data
    secrets:
      - miniosecret
  minio:
    image: minio/minio
    command: server /data
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: replica
        target: /data
volumes:
  data:
  replica:
secrets:
  miniosecret:
    external: true
