#!/bin/sh

export LITESTREAM_ACCESS_KEY_ID=${LITESTREAM_ACCESS_KEY_ID:-$(cat "${LITESTREAM_ACCESS_KEY_ID_FILE}")}
export LITESTREAM_SECRET_ACCESS_KEY=${LITESTREAM_SECRET_ACCESS_KEY:-$(cat "${LITESTREAM_SECRET_ACCESS_KEY_FILE}")}

echo "${LITESTREAM_CONFIG_CONTENT}" > /etc/litestream.yml

litestream $@
